remote_theme: pages-themes/midnight
plugins:
- jekyll-remote-theme


title: A.R.M.O.R # also site copyright appearing on footer
description: A comprehensive security measure image classification API that classifies (for now) 22 different types of common military armaments around the world posing threat to civilians on land.

author:
  name: Tanvir Ishraq Khan
